export const rewardIds = [
  ['diamond', 2],
  ['gold_ingot', 10],
  ['iron_ingot', 16],
  ['emerald', 3],
  ['lapis_lazuli', 15],
  ['experience_bottle', 5],
  ['name_tag', 1],
  ['golden_apple', 1],
  ['iron_horse_armor', 1],
  ['cooked_porkchop', 16],
  ['dirt', 32],
  ['cobblestone', 64],
  ['bucket', 1],
  ['ender_pearl', 2],
  ['cooked_beef', 10],
  ['cooked_chicken', 10],
  ['copper_ingot', 10],
  ['potato', 10],
  [
    `minecraft:player_head{SkullOwner:{Id:[I;],Properties:{textures:[{Value:"<base64_texture_value>"}]}},display:{Name:'{"text":"Patryk Winkler","color":"gold","bold":true}'}}`,
    1,
    'Patryk Winkler',
  ],
];
