export const rewardIds = [
  ['diamond', 2, 'Diamenty'],
  ['gold_ingot', 10, 'Złoto'],
  ['iron_ingot', 16, 'Żelazo'],
  ['emerald', 3, 'Emeraldy'],
  ['lapis_lazuli', 15, 'Lazuryt'],
  ['experience_bottle', 5, 'Butelki doświadczenia'],
  ['name_tag', 1, 'Plakietka'],
  ['golden_apple', 1, 'Złote jabłko'],
  ['iron_horse_armor', 1, 'Zbroja dla konia'],
  ['cooked_porkchop', 16, 'Gotowana wieprzowina'],
  ['dirt', 32, 'Ziemia'],
  ['cobblestone', 64, 'Bruk'],
  ['bucket', 1, 'Wiadro'],
  ['ender_pearl', 2, 'Perła endermana'],
  ['cooked_beef', 10, 'Gotowana wołowina'],
  ['cooked_chicken', 10, 'Gotowany kurczak'],
  ['copper_ingot', 10, 'Miedź'],
  ['potato', 10, 'Ziemniaki'],
  [
    `minecraft:player_head{SkullOwner:{Id:[I;],Properties:{textures:[{Value:"<base64_texture_value>"}]}},display:{Name:'{"text":"Patryk Winkler","color":"gold","bold":true}'}}`,
    1,
    'Patryk Winkler',
  ],
];
